export const enProxy = {
  proxy: {
    title: 'API Proxy',
    description: 'Manage the local API proxy service.',
    save: 'Save Settings',
    copy: 'Copy',
    regenerate: 'Regenerate',
    regenerateConfirm: {
      title: 'Regenerate API Key?',
      description:
        'This will invalidate the current API key immediately. Any applications using the old key will stop working.',
      cancel: 'Cancel',
      confirm: 'Regenerate',
    },
    service: {
      title: 'Service Status',
      description: 'Control the local API proxy server.',
      running: 'Running',
      stopped: 'Stopped',
      start: 'Start Service',
      stop: 'Stop Service',
    },
    errors: {
      portInUse: 'The selected API proxy port is already in use by another process.',
      toggleFailed: 'The proxy service could not be started or stopped safely.',
    },
    config: {
      port: 'Listen Port',
      timeout: 'Request Timeout',
      api_key: 'API Key',
      auto_start: 'Auto Start with App',
      auto_start_desc: 'Start proxy service when application launches',
      local_access: 'Local access:',
      no_token_warning: '⚠️ API key is not set. Access is open to everyone!',
      show_key: 'Show',
      hide_key: 'Hide',
    },
    mapping: {
      title: 'Model Mapping',
      description: 'Map Claude models to Gemini models for routing.',
      maps_to: 'Maps to',
      restore: 'Restore Defaults',
    },
    examples: {
      title: 'Usage Examples',
      description: 'Example commands to call the local API proxy.',
    },
    diagnostics: {
      title: 'Proxy Health & Metrics',
      description: 'Live request metrics, runtime capacity state, and proxy health signals.',
      loading: 'Loading proxy diagnostics...',
      loadFailed: 'Proxy diagnostics could not be loaded right now.',
      summary: {
        totalRequests: 'Total Requests',
        successResponses: 'Successful Responses',
        errorResponses: 'Error Responses',
        successRate: 'Success Rate',
        avgLatency: 'Average Latency',
        activeAccounts: 'Active Accounts',
      },
      runtime: {
        capacityTitle: 'Capacity State',
        capacityHealthy: 'The proxy currently reports healthy request capacity.',
        capacityReason: 'Current capacity reason: {{reason}}',
        retryAfter: 'Retry after: {{seconds}}s',
        rateLimitsTitle: 'Cooldown & Rate Limits',
        rateLimitsSummary: '{{cooldowns}} cooling down · {{upstreamLocks}} upstream locks',
        parityTitle: 'Parity Overview',
        paritySummary: 'Parity: {{enabled}} · Shadow: {{shadow}} · No-go: {{noGo}}',
        parityCounters:
          '{{requests}} requests · {{mismatches}} mismatches · {{errors}} parity errors',
        healthTitle: 'Service Health',
        healthSummary: 'Proxy service state: {{state}} · {{message}}',
        enabled: 'enabled',
        disabled: 'disabled',
        none: 'None',
        lastErrorNone: 'No recent proxy error recorded.',
      },
    },
    toast: {
      started: 'Proxy service started',
      stopped: 'Proxy service stopped',
      toggleFailed: 'Proxy service action failed',
    },
  },
} as const;
