export const enSettings = {
  settings: {
    title: 'Settings',
    description: 'Manage application preferences.',
    general: 'General',
    connection: 'Connection',
    models: 'Models',
    operations: {
      tab: 'Operations',
      dataPortability: {
        title: 'Data Portability',
        description:
          'Export or import a portable encrypted bundle of legacy, cloud, and Codex account data.',
        lastDirectory: 'Last used directory',
        noDirectory: 'No export directory selected yet',
        exportButton: 'Export Bundle',
        importButton: 'Import Bundle',
      },
      shared: {
        cancel: 'Cancel',
        legacy: 'Legacy',
        cloud: 'Cloud',
        codex: 'Codex',
      },
      export: {
        title: 'Export Portable Bundle',
        description: 'Protect the portable export with a password before writing it to disk.',
        targetFile: 'Target file',
        password: 'Export password',
        passwordPlaceholder: 'Enter a password for this bundle',
        confirmButton: 'Create Export',
        successTitle: 'Portable bundle exported',
        successDescription:
          'Exported {{legacy}} legacy, {{cloud}} cloud, and {{codex}} Codex records.',
        failedTitle: 'Portable export failed',
        failedDescription: 'The portable bundle could not be created.',
        passwordRequired: 'Enter an export password before creating the portable bundle.',
      },
      import: {
        title: 'Import Portable Bundle',
        description:
          'Preview the bundle first, then apply a merge import without changing the active runtime selection.',
        sourceFile: 'Source file',
        password: 'Import password',
        passwordPlaceholder: 'Enter the bundle password',
        previewButton: 'Preview Import',
        applyButton: 'Apply Merge Import',
        mergeSummary: 'Merge plan',
        mergeLine: '{{label}}: {{created}} new / {{updated}} updated',
        successTitle: 'Portable bundle imported',
        successDescription:
          'Imported {{legacy}} legacy, {{cloud}} cloud, and {{codex}} Codex records.',
        failedTitle: 'Portable import failed',
        failedDescription: 'The portable bundle could not be applied.',
        previewFailedTitle: 'Import preview failed',
        previewFailedDescription: 'The portable bundle preview could not be prepared.',
        passwordRequired: 'Enter the import password before previewing this bundle.',
        invalidFileOrPassword:
          'The selected file could not be decrypted. Verify the password and the export file.',
        previewExpired: 'The import preview expired. Re-open the file and preview it again.',
      },
      activity: {
        title: 'Activity Log',
        description:
          'Structured operator events from account, proxy, update, and portability flows.',
        loading: 'Loading recent activity...',
        empty: 'No activity events match the current filter.',
        loadMore: 'Load More',
        actionLine: 'Action: {{action}} · Target: {{target}}',
        noTarget: 'No explicit target',
        outcomes: {
          success: 'Success',
          failure: 'Failure',
          info: 'Info',
        },
        categories: {
          all: 'All',
          cloud: 'Cloud',
          codex: 'Codex',
          proxy: 'Proxy',
          update: 'Update',
          operations: 'Operations',
        },
      },
    },
    appearance: {
      title: 'Appearance',
      description: 'Customize how Applyron Manager looks on your device.',
    },
    darkMode: 'Dark Mode',
    darkModeDescription: 'Enable dark mode for better viewing at night.',
    language: {
      title: 'Language',
      description: 'Select your preferred language.',
      english: 'English',
      turkish: 'Turkish',
    },
    managedIde: {
      title: 'Managed IDE',
      description: 'Choose the workspace Applyron Manager should treat as the default target.',
      antigravityLabel: 'Antigravity',
      antigravityDescription:
        'Uses your Antigravity Gemini workspace as the default managed target.',
      codexDescription:
        'Uses the official OpenAI VS Code extension and the live Codex workspace as the default managed target.',
      antigravityScope:
        'Default accounts view: Gemini pool, Antigravity actions, and Antigravity tray shortcuts.',
      codexScope:
        'Default accounts view: Codex pool, VS Code Codex status/actions, and Codex tray shortcuts.',
      selectionHintTitle: 'What does this setting change?',
      selectionHint:
        'It sets the default section on the Accounts page, the tray quick actions, and the default IDE target used by status/open commands.',
      controls: 'What it controls',
      selected: 'Selected default target',
      ready: 'Ready on this device',
      placeholder: 'Select target',
      unavailable: 'Unavailable',
    },
    about: {
      title: 'About',
      description: 'Application information.',
    },
    version: 'Version',
    platform: 'Platform',
    license: 'License',
    openLogDir: 'Open',
    startup: {
      title: 'Startup',
      description: 'Control application launch behavior at system startup.',
      auto_startup: 'Start with system',
      auto_startup_desc: 'Launch at sign-in and keep the app in the system tray',
      macos_hint:
        'macOS requires a signed app for Login Items to work. If auto-start fails, please sign the app or enable it manually in System Settings.',
    },
    shortcuts: {
      title: 'Keyboard Shortcuts',
      description: 'Core navigation and operator shortcuts available across the app.',
      items: {
        dashboard: 'Open Dashboard',
        accounts: 'Open Accounts',
        proxy: 'Open Proxy',
        settings: 'Open Settings',
        refreshAccounts: 'Refresh the active Accounts tab',
        toggleProxy: 'Toggle proxy service',
        reloadWindow: 'Reload the application window',
      },
    },
    proxy: {
      title: 'Upstream Proxy',
      description: 'Configure a proxy for outgoing requests to Google/Gemini APIs.',
      enable: 'Enable Upstream Proxy',
      url: 'Proxy URL',
      timeout: 'Request Timeout (Seconds)',
    },
    modelMapping: {
      title: 'Model Mapping',
      description:
        'Map Claude Code models to Antigravity models. Optimize cost and speed by routing requests intelligently.',
      claudeKeyword: 'Claude Model (Keyword)',
      targetGemini: 'Target Gemini Model',
      addPlaceholderKey: 'e.g. op-3',
      addPlaceholderValue: 'e.g. gemini-3-flash',
      noMappings: 'No custom mappings defined.',
      mapsTo: 'Maps to',
      default: 'Default',
      restoreDefaults: 'Restore Defaults',
    },
    modelVisibility: {
      title: 'Model Visibility',
      description:
        "Control which models are visible in account cards. Hidden models won't appear in the quota display.",
      searchPlaceholder: 'Search models...',
      showAll: 'Show All',
      hideAll: 'Hide All',
      reset: 'Reset to Defaults',
      save: 'Save Changes',
      noModels: 'No models found',
      modelsShown: '{{visible}} of {{total}} models visible',
      resultsCount: '{{count}} results',
      quotaManagement: 'Quota Management',
      hidden: 'Hidden',
      noModelsFound: 'No models found',
      totalModels: 'Total',
      visibleModels: 'Visible',
      hiddenModels: 'Hidden',
      saving: 'Saving...',
    },
    providerGroupings: {
      title: 'Provider Groupings',
      description: 'Group models by provider for better organization',
      enabled: 'Enable Provider Groupings',
      models: '{{count}} models',
      avgLabel: 'avg',
      resetLabel: 'reset',
      overall: 'Overall',
      healthy: 'Healthy',
      degraded: 'Degraded',
      limited: 'Limited',
      critical: 'Critical',
    },
    examples: {
      title: 'Usage Examples',
      description: 'Example commands to call the local API proxy.',
      curl: 'cURL',
      python: 'Python',
      copy: 'Copy',
      copied: 'Copied!',
      openai_protocol: 'OpenAI Protocol',
      anthropic_protocol: 'Anthropic Protocol',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Fast',
      pro: 'Pro',
      flash_preview: 'Preview',
      pro_high: 'Best',
      sonnet: 'Thinking',
      opus: 'Opus',
    },
    gateway: {
      title: 'API Proxy Service',
      description: 'Control the local API proxy server.',
      status_running: 'Running',
      status_stopped: 'Stopped',
      action_start: 'Start Service',
      action_stop: 'Stop Service',
      accounts_info: '{{count}} accounts available',
      port: 'Listen Port',
      port_hint: 'Default 8045, restart required to apply changes',
      timeout: 'Request Timeout',
      timeout_hint: 'Default 120s, range 30-600s',
      api_key: 'API Key',
      regenerate_key: 'Regenerate',
      regenerateConfirm: {
        title: 'Regenerate API Key?',
        description:
          'This will invalidate the current API key immediately. Any applications using the old key will stop working.',
        cancel: 'Cancel',
        confirm: 'Regenerate',
      },
      key_warning: 'Keep your API key secure. Do not share it.',
      auto_start: 'Auto Start with App',
      auto_start_desc: 'Start proxy service when application launches',
    },
    proxy_tab: 'Proxy',
    save: 'Save Settings',
    notifications: {
      saved: {
        title: 'Settings saved',
        description: 'Your configuration has been updated.',
      },
      saveError: {
        title: 'Error saving settings',
        fallback: 'Failed to save settings',
      },
    },
  },
} as const;
