export const trManagedIde = {
  managedIde: {
    title: 'VS Code Codex',
    description:
      'Resmi OpenAI VS Code uzantısı üzerinden Windows Local ve Remote-WSL Codex runtime durumlarını izleyin.',
    badges: {
      cached: 'Önbellek',
      running: 'Çalışıyor',
    },
    actions: {
      refresh: 'Durumu yenile',
      openIde: 'VS Code’u aç',
      openLogin: 'Codex girişini aç',
    },
    availability: {
      ready: 'Hazır',
      unsupported_platform:
        'Bu entegrasyon Windows üzerinde ve Windows VS Code ile eşleşen WSL ortamında kullanılabilir.',
      ide_not_found: 'VS Code stable kurulumu bulunamadı.',
      extension_not_found: 'Resmi OpenAI VS Code uzantısı bulunamadı.',
      codex_cli_not_found: 'Paketlenmiş Codex CLI bulunamadı.',
      app_server_unavailable: 'Codex app-server şu anda erişilebilir değil.',
      not_signed_in: 'Devam etmek için VS Code içinden Codex’e giriş yapın.',
    },
    session: {
      ready: 'Giriş yapıldı',
      requires_login: 'Giriş gerekli',
      unavailable: 'Kullanılamıyor',
    },
    installation: {
      ready: 'Hazır',
      needsAttention: 'İnceleme gerekli',
      unavailableTitle: 'Kurulum kullanılamıyor',
    },
    sections: {
      installation: 'Kurulum',
      installationDescription: 'VS Code stable kurulumunu ve resmi OpenAI uzantısını tespit edin.',
      session: 'Oturum',
      sessionDescription: 'Codex app-server üzerinden alınan salt-okunur oturum özeti.',
      quota: 'Limitler',
      quotaDescription: 'Canlı Codex kota ve kredi özeti.',
    },
    labels: {
      installation: 'Kurulum',
      session: 'Oturum',
      plan: 'Plan',
      serviceTier: 'Servis katmanı',
      agentMode: 'Ajan modu',
      lastUpdated: 'Son güncelleme',
      ideVersion: 'VS Code sürümü',
      extensionVersion: 'Uzantı sürümü',
      idePath: 'VS Code yolu',
      extensionPath: 'Uzantı yolu',
      accountType: 'Hesap türü',
      authMode: 'Kimlik doğrulama modu',
      activeRuntime: 'Etkin runtime',
      requiresOpenaiAuth: 'OpenAI kimlik doğrulaması gerekli',
      primaryWindow: 'Birincil pencere',
      secondaryWindow: 'İkincil pencere',
      credits: 'Krediler',
      limitName: 'Etkin limit',
      resetsAt: 'Sıfırlanma zamanı',
      additionalLimits: 'Ek limitler',
    },
    runtimes: {
      windowsLocal: 'Windows Local',
      wslRemote: 'WSL Remote',
    },
    empty: {
      noAccount: 'Giriş yapılmış bir hesap tespit edilmedi',
      unknown: 'Bilinmiyor',
      unavailable: 'Kullanılamıyor',
      noQuota: 'Henüz canlı bir limit anlık görüntüsü alınamadı.',
    },
    values: {
      yes: 'Evet',
      no: 'Hayır',
      unlimited: 'Sınırsız',
      creditsAvailable: 'Kredi mevcut',
      noCredits: 'Kredi yok',
    },
    toast: {
      refreshFailedTitle: 'Codex durumu yenilenemedi',
      openIdeFailedTitle: 'VS Code açılamadı',
      openLoginFailedTitle: 'Codex girişi açılamadı',
    },
  },
} as const;
