export const trProxy = {
  proxy: {
    title: 'API Proxy',
    description: 'Yerel API proxy hizmetini yönetin.',
    save: 'Ayarları Kaydet',
    copy: 'Kopyala',
    regenerate: 'Yeniden Üret',
    regenerateConfirm: {
      title: 'API Anahtarı yeniden üretilsin mi?',
      description:
        'Bu işlem mevcut API anahtarını hemen geçersiz kılacaktır. Eski anahtarı kullanan uygulamalar çalışmayı durdurur.',
      cancel: 'Vazgeç',
      confirm: 'Yeniden Üret',
    },
    service: {
      title: 'Hizmet Durumu',
      description: 'Yerel API proxy sunucusunu yönetin.',
      running: 'Çalışıyor',
      stopped: 'Durdu',
      start: 'Hizmeti Başlat',
      stop: 'Hizmeti Durdur',
    },
    errors: {
      portInUse: 'Seçilen API proxy portu başka bir işlem tarafından kullanılıyor.',
      toggleFailed: 'Proxy hizmeti güvenli şekilde başlatılamadı veya durdurulamadı.',
    },
    config: {
      port: 'Dinleme Portu',
      timeout: 'İstek Zaman Aşımı',
      api_key: 'API Anahtarı',
      auto_start: 'Uygulamayla Birlikte Başlat',
      auto_start_desc: 'Uygulama açıldığında proxy hizmetini başlat',
      local_access: 'Yerel erişim:',
      no_token_warning: '⚠️ API anahtarı ayarlanmadı. Erişim herkese açık!',
      show_key: 'Göster',
      hide_key: 'Gizle',
    },
    mapping: {
      title: 'Model Eşleme',
      description: 'Yönlendirme için Claude modellerini Gemini modellerine eşleyin.',
      maps_to: 'Şuna eşlenir',
      restore: 'Varsayılanları Geri Yükle',
    },
    examples: {
      title: 'Kullanım Örnekleri',
      description: 'Yerel API proxy çağırmak için örnek komutlar.',
    },
    diagnostics: {
      title: 'Proxy Sağlığı ve Metrikler',
      description:
        'Canlı istek metrikleri, çalışma zamanı kapasite durumu ve proxy sağlık sinyalleri.',
      loading: 'Proxy tanı bilgileri yükleniyor...',
      loadFailed: 'Proxy tanı bilgileri şu anda yüklenemedi.',
      summary: {
        totalRequests: 'Toplam İstek',
        successResponses: 'Başarılı Yanıt',
        errorResponses: 'Hatalı Yanıt',
        successRate: 'Başarı Oranı',
        avgLatency: 'Ortalama Gecikme',
        activeAccounts: 'Etkin Hesap',
      },
      runtime: {
        capacityTitle: 'Kapasite Durumu',
        capacityHealthy: 'Proxy şu anda sağlıklı istek kapasitesi bildiriyor.',
        capacityReason: 'Mevcut kapasite nedeni: {{reason}}',
        retryAfter: 'Tekrar deneme: {{seconds}} sn',
        rateLimitsTitle: 'Cooldown ve Rate Limit',
        rateLimitsSummary: '{{cooldowns}} cooldown · {{upstreamLocks}} upstream kilidi',
        parityTitle: 'Parity Özeti',
        paritySummary: 'Parity: {{enabled}} · Shadow: {{shadow}} · No-go: {{noGo}}',
        parityCounters: '{{requests}} istek · {{mismatches}} uyuşmazlık · {{errors}} parity hatası',
        healthTitle: 'Servis Sağlığı',
        healthSummary: 'Proxy servis durumu: {{state}} · {{message}}',
        enabled: 'açık',
        disabled: 'kapalı',
        none: 'Yok',
        lastErrorNone: 'Son dönemde kayıtlı proxy hatası yok.',
      },
    },
    toast: {
      started: 'Proxy hizmeti başlatıldı',
      stopped: 'Proxy hizmeti durduruldu',
      toggleFailed: 'Proxy hizmeti işlemi başarısız oldu',
    },
  },
} as const;
