export const trSettings = {
  settings: {
    title: 'Ayarlar',
    description: 'Uygulama tercihlerini yönetin.',
    general: 'Genel',
    connection: 'Bağlantı',
    models: 'Modeller',
    operations: {
      tab: 'Operasyonlar',
      dataPortability: {
        title: 'Veri Taşınabilirliği',
        description:
          'Legacy, cloud ve Codex hesap verilerinin taşınabilir şifreli paketini dışa aktarın veya içe alın.',
        lastDirectory: 'Son kullanılan klasör',
        noDirectory: 'Henüz dışa aktarma klasörü seçilmedi',
        exportButton: 'Paketi Dışa Aktar',
        importButton: 'Paketi İçe Al',
      },
      shared: {
        cancel: 'İptal',
        legacy: 'Legacy',
        cloud: 'Cloud',
        codex: 'Codex',
      },
      export: {
        title: 'Taşınabilir Paket Dışa Aktar',
        description: 'Diske yazmadan önce taşınabilir çıktıyı parola ile koruyun.',
        targetFile: 'Hedef dosya',
        password: 'Dışa aktarma parolası',
        passwordPlaceholder: 'Bu paket için parola girin',
        confirmButton: 'Dışa Aktarmayı Oluştur',
        successTitle: 'Taşınabilir paket dışa aktarıldı',
        successDescription:
          '{{legacy}} legacy, {{cloud}} cloud ve {{codex}} Codex kaydı dışa aktarıldı.',
        failedTitle: 'Taşınabilir dışa aktarma başarısız oldu',
        failedDescription: 'Taşınabilir paket oluşturulamadı.',
        passwordRequired: 'Taşınabilir paketi oluşturmadan önce dışa aktarma parolası girin.',
      },
      import: {
        title: 'Taşınabilir Paket İçe Al',
        description:
          'Önce paketi önizleyin, sonra merge import uygulayın. Paket etkin bir Codex hesabı içeriyorsa Applyron mümkün olduğunda bunu seçili runtime tarafına geri yükler.',
        sourceFile: 'Kaynak dosya',
        password: 'İçe aktarma parolası',
        passwordPlaceholder: 'Paket parolasını girin',
        previewButton: 'İçe Aktarmayı Önizle',
        applyButton: 'Merge Import Uygula',
        mergeSummary: 'Merge planı',
        mergeLine: '{{label}}: {{created}} yeni / {{updated}} güncellendi',
        successTitle: 'Taşınabilir paket içe aktarıldı',
        successDescription:
          '{{legacy}} legacy, {{cloud}} cloud ve {{codex}} Codex kaydı içe aktarıldı.',
        failedTitle: 'Taşınabilir içe aktarma başarısız oldu',
        failedDescription: 'Taşınabilir paket uygulanamadı.',
        previewFailedTitle: 'İçe aktarma önizlemesi başarısız oldu',
        previewFailedDescription: 'Taşınabilir paket önizlemesi hazırlanamadı.',
        passwordRequired: 'Bu paketi önizlemeden önce içe aktarma parolasını girin.',
        invalidFileOrPassword:
          'Seçilen dosyanın şifresi çözülemedi. Parolayı ve dışa aktarma dosyasını doğrulayın.',
        previewExpired:
          'İçe aktarma önizlemesinin süresi doldu. Dosyayı yeniden açıp tekrar önizleyin.',
        restoreApplied: 'Etkin Codex hesabı {{runtime}} tarafına geri yüklendi.',
        restoreStoredOnlyRuntimeSelectionRequired:
          'Etkin Codex hesabı havuza aktarıldı, ancak canlı geri yükleme için önce bir Codex runtime tarafı seçmeniz gerekiyor.',
        restoreStoredOnlyRuntimeUnavailable:
          'Etkin Codex hesabı havuza aktarıldı, ancak bu cihazda uygun bir Codex runtime bulunamadığı için canlı geri yükleme yapılamadı.',
        restoreSkippedNoActiveCodex:
          'Paket içinde geri yüklenecek etkin bir Codex hesabı işaretlenmemişti.',
        restoreWarningMultipleActive:
          'Paket içinde birden fazla etkin Codex kaydı bulunduğu için en güncel olan seçildi.',
      },
      activity: {
        title: 'Aktivite Günlüğü',
        description:
          'Hesap, proxy, güncelleme ve taşınabilirlik akışlarından gelen yapılandırılmış operatör olayları.',
        loading: 'Son aktiviteler yükleniyor...',
        empty: 'Geçerli filtreyle eşleşen aktivite olayı yok.',
        loadMore: 'Daha Fazla Yükle',
        actionLine: 'Aksiyon: {{action}} · Hedef: {{target}}',
        noTarget: 'Açık hedef yok',
        outcomes: {
          success: 'Başarılı',
          failure: 'Başarısız',
          info: 'Bilgi',
        },
        categories: {
          all: 'Tümü',
          cloud: 'Cloud',
          codex: 'Codex',
          proxy: 'Proxy',
          update: 'Güncelleme',
          operations: 'Operasyon',
        },
      },
    },
    appearance: {
      title: 'Görünüm',
      description: 'Applyron Manager görünümünü cihazınızda özelleştirin.',
    },
    darkMode: 'Koyu Mod',
    darkModeDescription: 'Gece daha rahat kullanım için koyu modu etkinleştirin.',
    language: {
      title: 'Dil',
      description: 'Tercih ettiğiniz dili seçin.',
      english: 'İngilizce',
      turkish: 'Türkçe',
    },
    managedIde: {
      title: 'Yönetilen IDE',
      description: 'Applyron Manager’ın varsayılan hedef olarak kullanacağı çalışma alanını seçin.',
      antigravityLabel: 'Antigravity',
      antigravityDescription:
        'Antigravity Gemini çalışma alanını varsayılan yönetilen hedef yapar.',
      codexDescription:
        'Resmi OpenAI VS Code uzantısını ve canlı Codex çalışma alanını varsayılan yönetilen hedef yapar.',
      antigravityScope:
        'Varsayılan hesap görünümü: Gemini havuzu, Antigravity işlemleri ve Antigravity tepsi kısayolları.',
      codexScope:
        'Varsayılan hesap görünümü: Codex havuzu, VS Code Codex durum/işlemleri ve Codex tepsi kısayolları.',
      selectionHintTitle: 'Bu ayar neyi değiştirir?',
      selectionHint:
        'Hesaplar ekranında varsayılan açılan bölümü, tepsi hızlı işlemlerini ve durum/aç komutlarının varsayılan IDE hedefini belirler.',
      controls: 'Yönettiği alan',
      selected: 'Seçili varsayılan hedef',
      ready: 'Bu cihazda hazır',
      placeholder: 'Hedef seçin',
      unavailable: 'Kullanılamıyor',
    },
    about: {
      title: 'Hakkında',
      description: 'Uygulama bilgileri.',
    },
    version: 'Sürüm',
    platform: 'Platform',
    license: 'Lisans',
    openLogDir: 'Aç',
    startup: {
      title: 'Başlangıç',
      description: 'Sistem açılışındaki uygulama davranışını yönetin.',
      auto_startup: 'Sistemle başlat',
      auto_startup_desc: 'Oturum açıldığında başlat ve uygulamayı sistem tepsisinde tut',
      macos_hint:
        'macOS, Giriş Öğeleri için imzalı bir uygulama gerektirir. Otomatik başlangıç çalışmazsa uygulamayı imzalayın veya Sistem Ayarları içinden elle etkinleştirin.',
    },
    shortcuts: {
      title: 'Klavye Kısayolları',
      description: 'Uygulama genelinde kullanılabilen temel gezinme ve operatör kısayolları.',
      items: {
        dashboard: 'Dashboard ekranını aç',
        accounts: 'Hesaplar ekranını aç',
        proxy: 'Proxy ekranını aç',
        settings: 'Ayarlar ekranını aç',
        refreshAccounts: 'Etkin Hesaplar sekmesini yenile',
        toggleProxy: 'Proxy hizmetini aç veya kapat',
        reloadWindow: 'Uygulama penceresini yeniden yükle',
      },
    },
    proxy: {
      title: 'Yukarı Akış Proxy',
      description: 'Google/Gemini API istekleri için giden bağlantıya bir proxy tanımlayın.',
      enable: 'Yukarı Akış Proxyyi Etkinleştir',
      url: 'Proxy URL',
      timeout: 'İstek Zaman Aşımı (Saniye)',
    },
    modelMapping: {
      title: 'Model Eşleme',
      description:
        'Claude Code modellerini Antigravity modellerine eşleyin. İstekleri akıllıca yönlendirerek maliyet ve hızı optimize edin.',
      claudeKeyword: 'Claude Modeli (Anahtar Kelime)',
      targetGemini: 'Hedef Gemini Modeli',
      addPlaceholderKey: 'örn. op-3',
      addPlaceholderValue: 'örn. gemini-3-flash',
      noMappings: 'Özel eşleme tanımlanmadı.',
      mapsTo: 'Şuna eşlenir',
      default: 'Varsayılan',
      restoreDefaults: 'Varsayılanları Geri Yükle',
    },
    modelVisibility: {
      title: 'Model Görünürlüğü',
      description:
        'Hesap kartlarında hangi modellerin gösterileceğini kontrol edin. Gizlenen modeller kota görünümünde yer almaz.',
      searchPlaceholder: 'Model ara...',
      showAll: 'Tümünü Göster',
      hideAll: 'Tümünü Gizle',
      reset: 'Varsayılanlara Dön',
      save: 'Değişiklikleri Kaydet',
      noModels: 'Model bulunamadı',
      modelsShown: '{{visible}} / {{total}} model görünür',
      resultsCount: '{{count}} sonuç',
      quotaManagement: 'Kota Yönetimi',
      hidden: 'Gizli',
      noModelsFound: 'Model bulunamadı',
      totalModels: 'Toplam',
      visibleModels: 'Görünür',
      hiddenModels: 'Gizli',
      saving: 'Kaydediliyor...',
    },
    providerGroupings: {
      title: 'Sağlayıcı Grupları',
      description: 'Modelleri daha iyi düzenlemek için sağlayıcıya göre grupla',
      enabled: 'Sağlayıcı Gruplarını Etkinleştir',
      models: '{{count}} model',
      avgLabel: 'ort',
      resetLabel: 'sıfırla',
      overall: 'Genel',
      healthy: 'Sağlıklı',
      degraded: 'Düşük',
      limited: 'Sınırlı',
      critical: 'Kritik',
    },
    examples: {
      title: 'Kullanım Örnekleri',
      description: 'Yerel API proxy çağırmak için örnek komutlar.',
      curl: 'cURL',
      python: 'Python',
      copy: 'Kopyala',
      copied: 'Kopyalandı!',
      openai_protocol: 'OpenAI Protokolü',
      anthropic_protocol: 'Anthropic Protokolü',
      openai_tools: 'Cursor, Windsurf, NextChat',
      anthropic_tools: 'Claude Code CLI',
      flash: 'Hızlı',
      pro: 'Pro',
      flash_preview: 'Önizleme',
      pro_high: 'En İyi',
      sonnet: 'Düşünen',
      opus: 'Opus',
    },
    gateway: {
      title: 'API Proxy Hizmeti',
      description: 'Yerel API proxy sunucusunu yönetin.',
      status_running: 'Çalışıyor',
      status_stopped: 'Durdu',
      action_start: 'Hizmeti Başlat',
      action_stop: 'Hizmeti Durdur',
      accounts_info: '{{count}} hesap kullanılabilir',
      port: 'Dinleme Portu',
      port_hint: 'Varsayılan 8045, değişiklikler için yeniden başlatma gerekir',
      timeout: 'İstek Zaman Aşımı',
      timeout_hint: 'Varsayılan 120 sn, aralık 30-600 sn',
      api_key: 'API Anahtarı',
      regenerate_key: 'Yeniden Üret',
      regenerateConfirm: {
        title: 'API Anahtarı yeniden üretilsin mi?',
        description:
          'Bu işlem mevcut API anahtarını hemen geçersiz kılacaktır. Eski anahtarı kullanan uygulamalar çalışmayı durdurur.',
        cancel: 'Vazgeç',
        confirm: 'Yeniden Üret',
      },
      key_warning: 'API anahtarınızı güvende tutun. Paylaşmayın.',
      auto_start: 'Uygulamayla Birlikte Başlat',
      auto_start_desc: 'Uygulama açıldığında proxy hizmetini başlat',
    },
    proxy_tab: 'Proxy',
    save: 'Ayarları Kaydet',
    notifications: {
      saved: {
        title: 'Ayarlar kaydedildi',
        description: 'Yapılandırmanız güncellendi.',
      },
      saveError: {
        title: 'Ayarlar kaydedilemedi',
        fallback: 'Ayarlar kaydedilemedi',
      },
    },
  },
} as const;
