/// <reference types="vite/client" />

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare global {
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;
  const __APPLYRON_E2E__: boolean;

  interface GlobalThis {
    __APPLYRON_GOOGLE_CLIENT_ID__?: string;
    __APPLYRON_GOOGLE_CLIENT_SECRET__?: string;
  }

  interface OrpcClientPortBridge {
    postMessage: (message: string) => void;
    start: () => void;
    setOnMessage: (handler: ((data: unknown) => void) | null) => void;
  }

  interface ElectronBridge {
    startOrpcServer: () => void;
    getOrpcClientPort: () => OrpcClientPortBridge;
    onGoogleAuthCode: (callback: (code: string) => void) => () => void;
    onAppAlreadyRunning: (callback: () => void) => () => void;
    changeLanguage: (lang: string) => void;
  }

  interface ElectronTestBridge {
    setOrpcTestMode: (mode: 'cloudAccountsFailure' | null) => void;
    getOrpcTestMode: () => 'cloudAccountsFailure' | null;
  }

  interface Window {
    electron: ElectronBridge;
    electronTest?: ElectronTestBridge;
  }
}

export {};
